import Head from "next/head";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import Sentiment from "sentiment";

import FileSelector from "../components/FileSelector";
import TagCloud from "../components/TagCloud";
import WordInText from "../components/WordInText";

const WaveForm = dynamic(() => import("../components/WaveForm"), {
  ssr: false,
});

import { data } from "../data/transcription";
import getOccurrences from "../helpers/wordcloud";

const sentiment = new Sentiment();

export default function Home() {
  console.log(sentiment.analyze(data.transcript));
  const words = data.words;
  return (
    <div className={styles.container}>
      <Head>
        <title>Deepgram App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Visualize your audio</h1>
      {/* <FileSelector /> */}
      <TagCloud data={getOccurrences(data.words)} />
      <WaveForm url="samples/demo.mp3" />
      <div>
        {words.map((el, index) => {
          return (
            <WordInText
              key={index}
              word={el.word}
              onClick={() => {
                console.log(`Jump to ${el.start}`);
              }}
            />
          );
        })}
      </div>
    </div>
  );
}
